[package]
name = "ralg"
version = "0.1.2"
authors = ["Aleix Casanovas <aleics.casanovas@gmail.com>"]

description = "An uncomplicated library for Mathematics written in Rust."

[lib]
name = "ralg"
path = "src/lib.rs"

[dependencies]
num = "0.1.35"
rand = "0.3"
